server:
  servlet:
    context-path: /airpollution/authorize
  port: 9091
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1000KB
      max-file-size: 200000KB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/enquiry
    username: root
    password: welcome1
    driverClassName: com.mysql.cj.jdbc.Driver

